#!/bin/zsh

source ${HOME}/.profile

## Options section
setopt correct                                                  # Auto correct mistakes
setopt extendedglob                                             # Extended globbing. Allows using regular expressions with *
setopt nocaseglob                                               # Case insensitive globbing
setopt rcexpandparam                                            # Array expension with parameters
setopt nocheckjobs                                              # Don't warn about running processes when exiting
setopt numericglobsort                                          # Sort filenames numerically when it makes sense
setopt nobeep                                                   # No beep
setopt appendhistory                                            # Immediately append history instead of overwriting
setopt histignorealldups                                        # If a new command is a duplicate, remove the older one
setopt autocd                                                   # if only directory path is entered, cd there.

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'       # Case insensitive tab completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"         # Colored completion (different colors for dirs/files/etc)
zstyle ':completion:*' rehash true                              # automatically find new executables in path 
zstyle ':completion:*' accept-exact '*(N)'                      # Speed up completions
zstyle ':completion:*' use-cache on                             #
zstyle ':completion:*' cache-path ~/.zsh/cache                  #

HISTFILE=${HOME}/.zhistory
HISTSIZE=999999999
SAVEHIST=$HISTSIZE
WORDCHARS=${WORDCHARS//\/[&.;]}									# Don't consider certain characters part of the word
## Exports 

source ${HOME}/.config/zsh/exports

## Keybindings
source ${HOME}/.config/zsh/keybindings

## Alias section 
source ${HOME}/.config/zsh/alias

# Theming section  
# autoload -U compinit colors zcalc
# compinit -d
# colors

# enable substitution for prompt
setopt prompt_subst

# Prompt
PROMPT="%1~ ★ "

## Plugins section: Enable fish style features
# Use syntax highlighting
# source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# Use history substring search
# source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
source ${HOME}/.config/zsh/functions/**
source ${HOME}/.config/zsh/plugins/**

# NVM
source /usr/share/nvm/init-nvm.sh

# Unlock vault
# export $(cat ~/.keys/bitwarden.env)

PATH=${HOME}/bin:${PATH}:${HOME}/.local/bin:${HOME}/.gem/ruby/2.6.0/bin

# fbr - checkout git branch (including remote branches)
fbr() {                               

  local branches branch

  branches=$(git branch --all) &&

  branch=$(echo "$branches" |

           fzf-tmux -d $(( 2 + $(wc -l <<< "$branches") )) +m) &&

  git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")

}

# fshow - git commit browser
fshow() {
  git log --graph --color=always \
      --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
  fzf --ansi --no-sort --reverse --tiebreak=index --bind=ctrl-s:toggle-sort \
      --bind "ctrl-m:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
                {}
FZF-EOF"
}

alias bugrc="nvim ${HOME}/.config/bugwarrior/bugwarriorrc"
alias taskrc="nvim ${HOME}/.config/task/rc"
alias tmuxrc="nvim ${HOME}/.config/tmux/tmux.conf"
alias tridactylrc="nvim ${HOME}/.config/tridactyl/tridactylrc"
alias vimrc="nvim ${HOME}/.config/nvim/init.vim"
alias zshrc="nvim ${HOME}/.config/zsh/rc"

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'

function yay-commit () {
    local LIST=${HOME}/.config/packages/arch
    local GIT_HOME=${HOME}/.git 
    local GIT="--git-dir=${HOME}/.git --work-tree=${HOME}"

    yay --sync --noconfirm $1 \
    git --git-dir=${HOME}/.git --work-tree=${HOME} stash \
    && (grep -qxF ${1} ${LIST} \
       || echo $1 >> ${LIST}) \
    && git --git-dir=${HOME}/.git --work-tree=${HOME} add ${LIST} \
    && git --git-dir=${HOME}/.git --work-tree=${HOME} commit -m "pacman: add $1" \
    && git --git-dir=${HOME}/.git --work-tree=${HOME} push
    git --git-dir=${HOME}/.git --work-tree=${HOME} stash pop
}

# Inline the data location to share config with docker
alias task="nocorrect task rc.data.location=~/.local/share/task"

# Taskwarrior export
# Usage: te <filter> <args>
te () { 
  task $(grep "$1.filter" ~/.taskrc | cut -d '=' -f 2) "${@:2}" export
}

alias gc="git commit -m"
function gcf () {
  git add "${1}" && git commit -m "${@:2}"
}

alias less="bat"
alias ta="task add"
alias td="task do"
alias tl="task latest"
alias tw="task report:workflow"


git config --global alias.pully 'pull -s recursive -X ours'
git config --global alias.addall 'add -A'
git config --global alias.amend 'commit --amend --no-edit'

function gpf () {
 git push --force "$@"
}

function gcamaf () { 
  git addall \
    && git commit --amend --no-edit \
    && git push --force
}

function gca () {
  git add -A && git commit -m "$@"
}

# Vim is your pager now
export MANWIDTH=120
export PAGER="/bin/sh -c \"unset PAGER;col -b -x | \
      nvim -R -c 'set ft=man nomod nolist' -c 'map q :q<CR>' \
      -c 'map <SPACE> <C-D>' -c 'map b <C-U>' \
      -c 'Goyo' \
      -c 'nmap K :Man <C-R>=expand(\\\"<cword>\\\")<CR><CR>' -\""

# UTF support
LANG=en_US.utf8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE=C
LC_MONETARY=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=

if [[ -z "$TMUX" ]]; then
    if tmux has-session 2>/dev/null; then
        exec tmux attach
    else
        exec tmux
    fi
fi
