export PATH=$( find "${HOME}/.local/scripts" -type d -printf ":%p" ):$PATH

export BW_SESSION=$(cat "${HOME}/.secrets/bitwarden/session")
export TERM="tmux-256color"
export BSPWM_SOCKET="/tmp/bspwm-socket"
export BROWSER="$(which qutebrowser)"
export MPV_SOCKET="/tmp/mpv.socket"

export GDK_SCALE=3
export GDK_DPI_SCALE=0.5
export QT_AUTO_SCREEN_SET_FACTOR=0
export QT_SCALE_FACTOR=2
export QT_FONT_DPI=96

export MPV_SOCKET=/tmp/mpv.socket

export POLYBAR_HEIGHT=60

export KITTY_POPUP_WIDTH=2000
export KITTY_POPUP_HEIGHT=1000

export MANPAGER="/bin/sh -c \"col -b | nvim -c 'nnoremap Q :exit<CR> | set ft=man ts=8 nomod nolist nonu noma' -\""
