library: ~/.local/share/beets/library.db
directory: /storage/music
plugins:
  - missing

import:
  move: yes
  write: yes
  log: ~/.local/log/beets/beetslog.txt
  
duplicates:
  delete: yes
  tiebreak: 
    items: [bitrate]

paths:
    default: albums/$album - $albumartist [$year]/$track - $title
    singleton: singles/$artist - $title
