#!/bin/sh

DIR="$(cd "$(dirname "$0")" && pwd)"

[[ -f "${DIR}/device" ]] && source "$DIR/device"

xsetroot -solid "#000000"

gap=15
PANEL_HEIGHT=30

# This creates negative padding eaual to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT-gap))
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap
# bspc config border_width 2

# Various settings
bspc config gapless_monocle     false 
# Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  true
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config single_monocle        true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config active_border_color '#000000'
bspc config normal_border_color '#000000'
bspc config focused_border_color '#222222'

bspc rule -a 'floating-term' state=floating follow=on focus=on rectangle=1500x1000+0+0 center=true

# bspc rule -a mpv state=floating

# Autostart applications
# bspc desktop --focus V && alacritty &

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar example &

killall -q sxhkd
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
sxhkd &

[[ ! $(pgrep -u $UID kitty) ]] && kitty &
[[ ! $(pgrep -u $UID udiskie) ]] && udiskie &
