#!/bin/bash


pidof -o %PPID -x $0 >/dev/null && echo "ERROR: Script $0 already running" && exit 1

touch /tmp/barrierc
touch /tmp/barrierc-screen
touch /tmp/barrierc-connection

[[ $(pgrep -u $UID -x barrierc) ]] || nohup barrierc --no-daemon --log /tmp/barrierc --enable-crypto 10.0.0.1 &

tail -f /tmp/barrierc | awk '
  /connected/ { system("echo connected > /tmp/barrierc-connection") }
  /disconnected/ { system("echo disconnected > /tmp/barrierc-connection") }
  /entering/ { system("echo active > /tmp/barrierc-screen") }
  /leaving/ { system("echo inactive > /tmp/barrierc-screen") }
' &
