#!/bin/sh

dbus-send \
    --system \
    --type=method_call \
    --print-reply=literal \
    --dest=org.bluez /org/bluez/hci0 org.freedesktop.DBus.Properties.Set \
    string:org.bluez.Adapter1 \
    string:Powered \
    variant:boolean:true
