name: "Test Home Manager configuration."
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Link home.nix
      run: |
        mkdir -p $HOME/.config/nixpkgs
        ln -s $GITHUB_WORKSPACE/home.nix $HOME/.config/nixpkgs/home.nix
    - name: Install home-manager and realise home.nix
      run: |
        nix-shell '<home-manager>' -A install \
           -I home-manager=https://github.com/nix-community/home-manager/archive/master.tar.gz
